@startuml DER
skinparam linetype ortho
skinparam monochrome true
left to right direction

entity "users" {
  + id [PK]
  --
  nome : string
  email: string
  senha : string
}

entity "receita" {
  + id [PK]
  --
  conta_id [FK]
  categoria : string
  valor : decimal(12,2)
  data : date
  descricao : string
}

entity "despesa"{
    + id [PK]
  --
  conta_id [FK]
  categoria : string
  valor : decimal(12,2)
  data : date
  descricao : text
  recorrente : boolean
  pago : boolean
}


' Relacionamentos
users ||--o{ despesa : "1:N"
users ||--o{ receita : "1:N"


@enduml