@startuml Alvora Finanças - DER

!define primary_key(x) <b><color:#b8861b><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&key></color> x
!define column(x) <color:#efefef><&media-record></color> x

entity "users" {
  primary_key(id): bigint
  column(name): varchar(255)
  column(email): varchar(255)
  column(email_verified_at): timestamp
  column(password): varchar(255)
  column(remember_token): varchar(100)
  column(created_at): timestamp
  column(updated_at): timestamp
}

entity "receitas" {
  primary_key(id): bigint
  foreign_key(user_id): bigint
  column(descricao): varchar(255)
  column(categoria): varchar(255)
  column(valor): decimal(10,2)
  column(data_referencia): date
  column(is_recorrente): boolean
  column(created_at): timestamp
  column(updated_at): timestamp
}

entity "despesas" {
  primary_key(id): bigint
  foreign_key(user_id): bigint
  column(descricao): varchar(255)
  column(categoria): varchar(255)
  column(valor): decimal(10,2)
  column(data_referencia): date
  column(is_recorrente): boolean
  column(created_at): timestamp
  column(updated_at): timestamp
}

entity "password_reset_tokens" {
  primary_key(email): varchar(255)
  column(token): varchar(255)
  column(created_at): timestamp
}

entity "personal_access_tokens" {
  primary_key(id): bigint
  column(tokenable_type): varchar(255)
  column(tokenable_id): bigint
  column(name): varchar(255)
  column(token): varchar(64)
  column(abilities): text
  column(last_used_at): timestamp
  column(expires_at): timestamp
  column(created_at): timestamp
  column(updated_at): timestamp
}

users ||--o{ receitas : "possui"
users ||--o{ despesas : "possui"

@enduml
